### ISSUE TITLE
._dessert breaks the rest of the pattern that is used for testing.

### ISSUE THREAD

**Issue by kevinmcalear** [learn-co-curriculum/fewpjs-oo-initializing-instances#2]
https://github.com/learn-co-curriculum/fewpjs-oo-initializing-instances/blob/master/test/indexTest.js#L33

**Comment by ipc103** [comment]
Hey @kevinmcalear - thanks for opening this. Can you add a bit more context? Is the issue that we're testing a property that is meant to be private?

**Comment by kevinmcalear** [comment]
```
it("creates a new dinner with the correct parameters", () => {
    newdinner = new Dinner('balsamic salad', 'consomme', 'filet mignon', 'cheesecake')
    expect(newdinner.salad).to.equal('balsamic salad')
    expect(newdinner.soup).to.equal('consomme')
    expect(newdinner.entree).to.equal('filet mignon')
    expect(newdinner._dessert).to.equal('cheesecake')
  })
```

the `._dessert` issue I opened  is in context of the other attributes not following the `._attribute` convention. All of the rest of the attributes in this text do not follow the underscore convention so we might want to change `._dessert` to `.dessert`.

Sorry for the lack of context!

**Comment by jenmyers** [comment]
We have standardized this naming. Thanks for the heads-up.
